name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [backend, frontend]
        node-version: [18, 20]
    env:
      DB_URL: ${{ secrets.DB_URL }}
    defaults:
      run:
        working-directory: ${{ matrix.component }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: 'npm'
          cache-dependency-path: ${{ matrix.component }}/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
